sudo: false
language: python

python: "3.6"

cache:
  - pip
  - apt

# install dependencies
# install:
#   - pip install -r requirements.txt
#   - pip install -r dev-requirements.txt

# run tests
script:
  - echo "Run tests here"

before_deploy:
  - BRANCH=$(echo "$TRAVIS_BRANCH" | tr / _) # remove '/' from branch name
  - zip from_travis_$BRANCH.zip lambda_function.py

deploy:
  provider: lambda
  access_key_id: AKIAJBHFBXFFAYGMLKWQ
  secret_access_key:
    secure: W0inbJTqmFfpvPoIlHIfMiZs8WeCx0z95e4MnDxtEz+RUSP3q1j8tjoCV7r5nTlgySvob8NKC+PziA6NlKy6Dz+seIojf8Seev8CL5UIY1gIUtrZSG8nnfIVjrLkqTM4UlMiJlcwCSOozpivybCwj9KA3Y8otcuIJtPj5OL3/dC6KW9sUi7RhiO9v1CNJHHdbYMKevj7VDXTRD3CJXwodO+imBoDf8HVkLUPjIXvvcOS/f3WT7eTcX/QPo3xjayS9clJPpp1NKOTn/GSEzZY9hDOTaVk9381LZDH0z8y4LVpOWfarHUBs0XErxAH7nz+Ox1NR9FYxT69h8e1MqDLyI1RG5cj7n2K5hBQU64+SpziezcenoSGU6SlMuT4qEm/zXy22CvemAkDl/b2TlEcmD0BP3zQ4hnRRlhEhoUNCQmfOAL0ldG2ZNgcfOYSGt4QQKZomRa9B4mYP59mJk6dXS7czja6suvvcv7aU54yciXsg/fzFe0CrQakXboUus0zmZQ4eBTJGQYpi5s6ZyqClxj5YjKXVi8N1P6Ytoxp3WMvPbf7AfWhSwFF3VU/Iemlit7sSZhDFpQJVDfPKbX4L7f+CxH0IEaBUJFCKMzi/S47d6+byWrdioMEl3qBzAEQSKV87w0krwu9i1I4SVNl6If6ATe0wkHVcc6VQa0nPTQ=
  function_name: "from_travis_${BRANCH}"
  region: "us-east-2"
  role: "arn:aws:iam::707767160287:role/dos-indexd-lambda-dev"
  runtime: "python3.6"
  publish: true # create a new version of the lambda function
  zip: "from_travis_${BRANCH}.zip"
  handler_name: "lambda_function.lambda_handler"
  on:
    branch: test/travis
