sudo: false
language: python

python: "3.6"

cache:
  - pip
  - apt

# install dependencies
# install:
#   - pip install -r requirements.txt
#   - pip install -r dev-requirements.txt

# run tests
script:
  - echo "Run tests here"

before_deploy:
  - BRANCH=$(echo "$TRAVIS_BRANCH" | tr / _) # remove '/' from branch name
  - zip from_travis_$BRANCH.zip lambda_function.py
  # - mkdir -p to_upload
  # - zip to_upload/from_travis_$BRANCH.zip lambda_function.py

# deploy:
#   provider: s3
#   access_key_id: AKIAI2DDBSIFZD77A3XA
#   secret_access_key:
#     secure: qZEu8fQDhrjPP9C91DFsQLEWfx+HUK4BQr6KzQjvzXbV57KTYH69IJozl8RbXK0UbqPj7g7tHSSZU5VRYZ3qEZNFJQbj3ryrPw8apJ0bFGg5qobU7B1FsvejlJpYBAiMJESW9No20vK4ufr+z7pEnwI58xJPDHbAPQmOinFcHrYwSvq5adLWLaq4vQ5OpY+DXEyjzIUhNoMX+iwSovPMvm1XwzA1IEclD14VIhsz68YyG4wLadKDRuZyDiZy3uF/MfR22CMrXPkdBlov83a1rj3UeHohPFZkrPCZK4P+ZPtM+seZg9qSdWKwDZHa6wvLi2As658Ox7dNM/VIPJ7daIsiLxjesi90CbAbdVIB+axHVvBa8dd5ioJowQkcsN1DXdLrKiJfeXkkWc0egfIh8j0jFpRjuD0bQC1H5aVMl8ZKdT7KUdHoHL/r3L7rugt6QzLrl1fYD8kEbbKc6ibRLjdRkRPo+aDeTmTzzDQTbHeC5G34GkZHsLUN66PkZ2HUEEEKrTr0wrpPGLUrxcVQSd2dZzc13DevPbkRWVE9OVj4ymrCsZni7l5UCCSMCKsbew8Ku17W3jUg+83NTD83/HfUqkQCsjpGon2Na7XoyJm5z46q/vaQu2g9SEjJFhToNTck0+41bWklTUwqbvTbZYlGDNpVXVWMEhKyNqa6JI8=
#   bucket: pauline-upload-test
#   local-dir: to_upload
#   skip_cleanup: true
#   on:
#     branch: test/travis

deploy:
  provider: lambda
  access_key_id: AKIAI2DDBSIFZD77A3XA
  secret_access_key:
    secure: qZEu8fQDhrjPP9C91DFsQLEWfx+HUK4BQr6KzQjvzXbV57KTYH69IJozl8RbXK0UbqPj7g7tHSSZU5VRYZ3qEZNFJQbj3ryrPw8apJ0bFGg5qobU7B1FsvejlJpYBAiMJESW9No20vK4ufr+z7pEnwI58xJPDHbAPQmOinFcHrYwSvq5adLWLaq4vQ5OpY+DXEyjzIUhNoMX+iwSovPMvm1XwzA1IEclD14VIhsz68YyG4wLadKDRuZyDiZy3uF/MfR22CMrXPkdBlov83a1rj3UeHohPFZkrPCZK4P+ZPtM+seZg9qSdWKwDZHa6wvLi2As658Ox7dNM/VIPJ7daIsiLxjesi90CbAbdVIB+axHVvBa8dd5ioJowQkcsN1DXdLrKiJfeXkkWc0egfIh8j0jFpRjuD0bQC1H5aVMl8ZKdT7KUdHoHL/r3L7rugt6QzLrl1fYD8kEbbKc6ibRLjdRkRPo+aDeTmTzzDQTbHeC5G34GkZHsLUN66PkZ2HUEEEKrTr0wrpPGLUrxcVQSd2dZzc13DevPbkRWVE9OVj4ymrCsZni7l5UCCSMCKsbew8Ku17W3jUg+83NTD83/HfUqkQCsjpGon2Na7XoyJm5z46q/vaQu2g9SEjJFhToNTck0+41bWklTUwqbvTbZYlGDNpVXVWMEhKyNqa6JI8=
  function_name: "from_travis_${BRANCH}"
  region: "us-east-2"
  role: "arn:aws:iam::707767160287:role/dos-indexd-lambda-dev"
  runtime: "python3.6"
  publish: true # create a new version of the lambda function
  zip: "from_travis_${BRANCH}.zip"
  handler_name: "lambda_function.lambda_handler"
  on:
    branch: test/travis
